env:
    - TRAVIS_FLAVOR=default
    - TRAVIS_FLAVOR=core_integration
    - TRAVIS_FLAVOR=checks_mock
    - TRAVIS_FLAVOR=activemq
    - TRAVIS_FLAVOR=apache
    - TRAVIS_FLAVOR=cassandra FLAVOR_VERSION=2.0.13
    - TRAVIS_FLAVOR=cassandra FLAVOR_VERSION=2.1.3
    - TRAVIS_FLAVOR=couchdb
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=0.90.13
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.0.3
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.1.2
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.2.4
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.3.9
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.4.5
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.5.2
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.6.2
    - TRAVIS_FLAVOR=elasticsearch FLAVOR_VERSION=1.7.4
    - TRAVIS_FLAVOR=etcd
    - TRAVIS_FLAVOR=fluentd
    - TRAVIS_FLAVOR=go_expvar
    # FIXME: cannot enable gearman on Travis right now
    # because it needs boost
    # - TRAVIS_FLAVOR=gearman
    - TRAVIS_FLAVOR=haproxy FLAVOR_VERSION=1.3.27
    - TRAVIS_FLAVOR=haproxy FLAVOR_VERSION=1.4.26
    - TRAVIS_FLAVOR=haproxy FLAVOR_VERSION=1.5.11
    - TRAVIS_FLAVOR=lighttpd
    - TRAVIS_FLAVOR=memcache
    - TRAVIS_FLAVOR=mongo FLAVOR_VERSION=2.6.9
    - TRAVIS_FLAVOR=mongo FLAVOR_VERSION=3.0.1
    - TRAVIS_FLAVOR=mysql
    - TRAVIS_FLAVOR=network
    - TRAVIS_FLAVOR=nginx FLAVOR_VERSION=1.6.2
    - TRAVIS_FLAVOR=nginx FLAVOR_VERSION=1.7.11
    - TRAVIS_FLAVOR=pgbouncer
    - TRAVIS_FLAVOR=phpfpm
    - TRAVIS_FLAVOR=postgres FLAVOR_VERSION=9.0.19
    - TRAVIS_FLAVOR=postgres FLAVOR_VERSION=9.1.15
    - TRAVIS_FLAVOR=postgres FLAVOR_VERSION=9.2.10
    - TRAVIS_FLAVOR=postgres FLAVOR_VERSION=9.3.6
    - TRAVIS_FLAVOR=postgres FLAVOR_VERSION=9.4.1
    - TRAVIS_FLAVOR=rabbitmq
    - TRAVIS_FLAVOR=redis FLAVOR_VERSION=2.4.18
    - TRAVIS_FLAVOR=redis FLAVOR_VERSION=2.6.17
    - TRAVIS_FLAVOR=redis FLAVOR_VERSION=2.8.19
# Compilation takes too much time on Travis
#   - TRAVIS_FLAVOR=riak
    - TRAVIS_FLAVOR=snmpd
    - TRAVIS_FLAVOR=ssh
    - TRAVIS_FLAVOR=supervisord
    - TRAVIS_FLAVOR=sysstat
# FIXME: reenable, but right now cannot run on Travis because
# hugepages are enabled
#    - TRAVIS_FLAVOR=tokumx
    - TRAVIS_FLAVOR=tomcat # JMX testing machine / need the other ones before
    - TRAVIS_FLAVOR=varnish FLAVOR_VERSION=3.0.7
    - TRAVIS_FLAVOR=varnish FLAVOR_VERSION=4.0.3
    - TRAVIS_FLAVOR=zookeeper FLAVOR_VERSION=3.4.7
    - TRAVIS_FLAVOR=zookeeper FLAVOR_VERSION=3.3.6

command:
    - echo "Running flavor $TRAVIS_FLAVOR"
    - bundle exec rake ci:run
