# blacklist
branches:
  except:
    - check-haproxy
services:
  - mysql
  - elasticsearch
  - memcache
before_script:
  - mysql -e "create user 'dog'@'localhost' identified by 'dog'"
language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install openjdk-6-jre-headless
  - sudo apt-get install sysstat
  - sudo apt-get install haproxy
  - sudo apt-get install python-mysqldb
  - sudo apt-get install tomcat6
  - sudo apt-get install solr-tomcat
  - sudo apt-get install nginx
  - sudo apt-get install apache2
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install . --use-mirrors
before_script:
  - curl -L https://raw.github.com/DataDog/dd-agent/master/tests/haproxy.cfg > /tmp/haproxy.cfg
  - sudo service haproxy restart
  # - curl -L http://mirrors.ibiblio.org/apache/tomcat/tomcat-7/v7.0.34/bin/apache-tomcat-7.0.34.tar.gz | tar -C /tmp -xzf - && mv /tmp/apache-tomcat-7.0.34/ /tmp/apache-tomcat-7 && echo 'export CATALINA_OPTS="-Dcom.sun.management.jmxremote.port=8091 -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.password.file=/tmp/apache-tomcat-7/conf/jmxremote.password -Dcom.sun.management.jmxremote.access.file=/tmp/apache-tomcat-7/conf/jmxremote.access -Dcom.sun.management.jmxremote.ssl=false" export CATALINA_OUT="/tmp/apache-tomcat-7/catalina.out"' > /tmp/apache-tomcat-7/bin/setenv.sh && echo 'monitorRole readonly' > /tmp/apache-tomcat-7/conf/jmxremote.access && echo 'monitorRole tomcat' > /tmp/apache-tomcat-7/conf/jmxremote.password && chmod 400 /tmp/apache-tomcat-7/conf/jmxremote.password
  # - sudo bash -c "echo 'monitorRole readonly' > /etc/solr/conf/jmxremote.access && chmod 400 /etc/solr/conf/jmxremote.access" 
  # - sudo bash -c "echo 'monitorRole solr' > /etc/solr/conf/jmxremote.password && chmod 400 /etc/solr/conf/jmxremote.password" 
  - sudo bash -c "curl -L https://raw.github.com/DataDog/dd-agent/master/tests/tomcat_cfg.xml > /etc/tomcat6/server.xml"
  - sudo bash -c "curl -L https://raw.github.com/DataDog/dd-agent/master/tests/tomcat6 >> /etc/default/tomcat6"
  - sudo service nginx stop
  - sudo bash -c "curl -L https://raw.github.com/DataDog/dd-agent/master/tests/nginx.conf > /etc/nginx/conf.d/default.conf"
  - sudo service apache2 stop
  - sudo bash -c "curl -L https://raw.github.com/DataDog/dd-agent/master/tests/apache/ports.conf > /etc/apache2/ports.conf"
  - sudo bash -c "curl -L https://raw.github.com/DataDog/dd-agent/master/tests/apache/apache.conf > /etc/apache2/apache.conf"
  - sudo mkdir -p /etc/dd-agent/
  - sudo install -d -o "$(id -u)" /var/log/datadog
  - sudo bash -c "curl -L https://raw.github.com/DataDog/dd-agent/master/datadog.conf.example > /etc/dd-agent/datadog.conf"
  - sudo service tomcat6 restart
  - sudo service apache2 start
  - sudo service nginx start
env:
  - DB=redis
script: nosetests -A 'not windows' tests
